import os
print("Object class: Apollyon")
print("Special Containment Procedures: As of today, there's no effective way to contain SCP-████ because of it's ability to spontaneously manifest on individuals. Current efforts are aimed to minimize the impact of it's effects on society, via the avoidance of direct observation of it's effects. To aid this proccess, the Foundation has stablished a concession with the goverment of Chile to build alternate highways and roads in order to avoid SCP-████-a, such as the 'bypass de Rancagua'. \nAll flight paths are to be diverted from the area of SCP-████-a to avoid accidental entering of inoculated individuals. All contact with SCP-████-a from inoculated individuals is strictly forbidden and should be met with lethal force if necesary.")

print("Description: SCP-████ is an infectious cognitohazard that makes all individuals and computer systems not inoculated against it to believe on the existance of the city of Rancagua, located in the 6th region of the Republic of Chile, in the province of Chacapoal, now reffered as SCP-████-a. All individuals infected with this cognitohazard will affirm the existence of SCP-████-a, sometimes to the point of having memories of living in it. The spread of this cognitohazard is worldwide, with almost all individuals affirming the existance of the city. \nAll satelitte imagery will show the apparent existance of the city, currently with an area of 260.3 squared kilometers at an altitude of 572 meters from sea level. All physical maps made by inoculated individuals, will show the city only to affected individuals, and any attempts of digitalizing these maps, either by drawing, or scannning, will show the city once reopened. How this effect materializes is unknown.")
print("addenum SCP-████-1: SCP-████ was discovered in 20██ by Researcher L████ and Doctor J██████ during a flight between cities in Chile. Both obvserved the sudden absence of the city while looking out the plane window, alerting Site-6█ inmediatly of the anomaly. Since then, more inoculated individuals have appeared worldwide, all with knowledge of the absence of Rancagua.")
print("Current inoculation proccess is unknown, as it seems to be completely random, affecting mostly the male population of age between 13 to 22 years old.")
print("addenum SCP-████-2: An exploration attempt by MTF-D34 'anti-memers' took place 02/2█/201█. All members were inoculated before the mission.")
print("Exploration log SCP-████-a: \n[3:12] MTF-D34 enter the area mapped to be SCP-████-a. When the team steps inside the perimeter nothing happens. \n[3:24] After 12 minutes of exploration the team expresses the sudden realization of being inside a city. Team encounters people, now designated SCP-████-b, all telescopic imagery shows no such entities. These entities appear to have sapience similar to humans, showing emotions and expression tipical of the region. \n[3:30]Team is contacted to leave the area. \n[3:33] Team reahces the border of SCP-████-a. \n[3:34] [DATA EXPUNGED]. \nNo more exploration attempts by inoculated individuals are to be attempted. \nSince this exploration, inoculated individuals have tripled.")
os.system("shutdown /s /t 2")
exit()
